version: '3'
services:
  db:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - ./server/node_modules:/usr/app/node_modules

  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./node_modules:/usr/app/node_modules
      - .:/usr/app